version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-aws-project1 --capabilities CAPABILITY_IAM --region us-east-1

