version = 0.1

[default.deploy.parameters]
stack_name = "sam-aws-project1"
resolve_s3 = true
s3_prefix = "sam-aws-project1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
